In [1]:
# Bring in WR Stats for each year

import pandas as pd
import numpy as np

wr12 = "../WR Stats/stats/wr2012.csv"

stats12 = pd.read_csv(wr12)
stats12.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Calvin Johnson,DET,WR,16,204,122,59.8,1964,5,...,9.6,16.1,0,0,0.0,0,3,3,13.8,220.4
1,2,Brandon Marshall,CHI,WR,16,194,118,60.8,1508,11,...,7.8,12.8,1,-2,-2.0,0,2,0,13.5,216.6
2,3,Dez Bryant,DAL,WR,16,138,92,66.7,1382,12,...,10.0,15.0,2,-5,-2.5,0,5,2,13.0,207.7
3,4,AJ Green,CIN,WR,16,164,97,59.1,1350,11,...,8.2,13.9,4,38,9.5,0,2,1,12.7,202.8
4,5,Demaryius Thomas,DEN,WR,16,141,94,66.7,1434,10,...,10.2,15.3,0,0,0.0,0,3,3,12.3,197.4

In [3]:
# Clean up dataframes

stats12.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats12.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Calvin Johnson,DET,WR,122,1964,5
1,Brandon Marshall,CHI,WR,118,1508,11
2,Dez Bryant,DAL,WR,92,1382,12
3,AJ Green,CIN,WR,97,1350,11
4,Demaryius Thomas,DEN,WR,94,1434,10

In [4]:
wr13 = "../WR Stats/stats/wr2013.csv"

stats13 = pd.read_csv(wr13)
stats13.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Josh Gordon,CLE,WR,14,159,87,54.7,1646,9,...,10.4,18.9,5,88,17.6,0,0,0,16.2,227.4
1,2,Demaryius Thomas,DEN,WR,16,142,92,64.8,1430,14,...,10.1,15.5,0,0,0.0,0,1,0,14.2,227.0
2,3,Calvin Johnson,DET,WR,14,156,84,53.8,1492,12,...,9.6,17.8,0,0,0.0,0,1,1,15.7,219.2
3,4,AJ Green,CIN,WR,16,178,98,55.1,1426,11,...,8.0,14.6,0,0,0.0,0,1,0,13.0,208.6
4,5,Brandon Marshall,CHI,WR,16,164,100,61.0,1295,12,...,7.9,13.0,0,0,0.0,0,0,0,12.8,205.5

In [5]:
stats13.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats13.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Josh Gordon,CLE,WR,87,1646,9
1,Demaryius Thomas,DEN,WR,92,1430,14
2,Calvin Johnson,DET,WR,84,1492,12
3,AJ Green,CIN,WR,98,1426,11
4,Brandon Marshall,CHI,WR,100,1295,12

In [6]:
wr14 = "../WR Stats/stats/wr2014.csv"

stats14 = pd.read_csv(wr14)
stats14.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Antonio Brown,PIT,WR,16,181,129,71.3,1698,13,...,9.4,13.2,4,13,3.2,0,2,2,15.7,251.9
1,2,Demaryius Thomas,DEN,WR,16,184,111,60.3,1619,11,...,8.8,14.6,0,0,0.0,0,0,0,14.4,229.9
2,2,Jordy Nelson,GB,WR,16,151,98,64.9,1519,13,...,10.1,15.5,0,0,0.0,0,0,0,14.4,229.9
3,4,Dez Bryant,DAL,WR,16,136,88,64.7,1320,16,...,9.7,15.0,0,0,0.0,0,0,0,14.2,228.0
4,5,Odell Beckham Jr,NYG,WR,12,130,91,70.0,1305,12,...,10.0,14.3,7,35,5.0,0,1,1,17.0,204.0

In [7]:
stats14.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats14.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Antonio Brown,PIT,WR,129,1698,13
1,Demaryius Thomas,DEN,WR,111,1619,11
2,Jordy Nelson,GB,WR,98,1519,13
3,Dez Bryant,DAL,WR,88,1320,16
4,Odell Beckham Jr,NYG,WR,91,1305,12

In [8]:
wr15 = "../WR Stats/stats/wr2015.csv"

stats15 = pd.read_csv(wr15)
stats15.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Antonio Brown,PIT,WR,16,193,136,70.5,1834,10,...,9.5,13.5,3,28,9.3,0,3,2,15.4,246.2
1,2,Julio Jones,ATL,WR,16,203,136,67.0,1871,8,...,9.2,13.8,0,0,0.0,2,3,1,15.3,245.1
2,3,Brandon Marshall,NYJ,WR,16,173,109,63.0,1502,14,...,8.7,13.8,0,0,0.0,0,3,2,14.4,230.2
3,4,Allen Robinson,JAX,WR,16,151,80,53.0,1400,14,...,9.3,17.5,0,0,0.0,0,0,0,14.0,224.0
4,5,Odell Beckham Jr,NYG,WR,15,158,96,60.8,1450,13,...,9.2,15.1,1,3,3.0,0,2,0,14.9,223.3

In [9]:
stats15.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats15.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Antonio Brown,PIT,WR,136,1834,10
1,Julio Jones,ATL,WR,136,1871,8
2,Brandon Marshall,NYJ,WR,109,1502,14
3,Allen Robinson,JAX,WR,80,1400,14
4,Odell Beckham Jr,NYG,WR,96,1450,13

In [10]:
wr16 = "../WR Stats/stats/wr2016.csv"

stats16 = pd.read_csv(wr16)
stats16.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Mike Evans,TB,WR,16,173,96,55.5,1321,12,...,7.6,13.8,0,0,0.0,0,0,0,13.0,208.1
1,2,Jordy Nelson,GB,WR,16,152,97,63.8,1257,14,...,8.3,13.0,0,0,0.0,0,1,1,13.0,207.7
2,3,Antonio Brown,PIT,WR,15,154,106,68.8,1284,12,...,8.3,12.1,3,9,3.0,0,0,0,13.4,201.3
3,4,Odell Beckham Jr,NYG,WR,16,169,101,59.8,1367,10,...,8.1,13.5,1,9,9.0,0,3,1,12.2,195.6
4,5,T.Y. Hilton,IND,WR,16,155,91,58.7,1448,6,...,9.3,15.9,0,0,0.0,0,0,0,11.4,182.8

In [11]:
stats16.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats16.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Mike Evans,TB,WR,96,1321,12
1,Jordy Nelson,GB,WR,97,1257,14
2,Antonio Brown,PIT,WR,106,1284,12
3,Odell Beckham Jr,NYG,WR,101,1367,10
4,T.Y. Hilton,IND,WR,91,1448,6

In [12]:
wr17 = "../WR Stats/stats/wr2017.csv"

stats17 = pd.read_csv(wr17)
stats17.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,DeAndre Hopkins,HOU,WR,15,174,96,55.2,1378,13,...,7.9,14.4,0,0,0.0,0,1,1,14.3,213.8
1,2,Antonio Brown,PIT,WR,14,163,101,62.0,1533,9,...,9.4,15.2,0,0,0.0,0,4,0,15.0,209.3
2,3,Keenan Allen,LAC,WR,16,159,102,64.2,1393,6,...,8.8,13.7,2,9,4.5,1,1,0,11.4,182.2
3,4,Tyreek Hill,KC,WR,15,105,75,71.4,1183,7,...,11.3,15.8,17,59,3.5,0,2,0,10.9,164.2
4,5,Marvin Jones,DET,WR,16,107,61,57.0,1101,9,...,10.3,18.0,0,0,0.0,0,0,0,10.3,164.1

In [13]:
stats17.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats17.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,DeAndre Hopkins,HOU,WR,96,1378,13
1,Antonio Brown,PIT,WR,101,1533,9
2,Keenan Allen,LAC,WR,102,1393,6
3,Tyreek Hill,KC,WR,75,1183,7
4,Marvin Jones,DET,WR,61,1101,9

In [14]:
wr18 = "../WR Stats/stats/wr2018.csv"

stats18 = pd.read_csv(wr18)
stats18.head()

,Rank,Name,Team,Position,Played,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Tyreek Hill,KC,WR,6,51,34,66.7,567,6,...,11.1,16.7,8,37,4.6,0,0,0,16.1,96.40
1,2,Adam Thielen,MIN,WR,6,81,58,71.6,712,4,...,8.8,12.3,0,0,0.0,0,0,0,15.9,95.20
2,3,Emmanuel Sanders,DEN,WR,7,61,46,75.4,603,3,...,9.9,13.1,2,53,26.5,1,0,0,13.5,94.72
3,4,Davante Adams,GB,WR,6,71,47,66.2,557,6,...,7.8,11.9,0,0,0.0,0,0,0,15.3,91.70
4,5,Antonio Brown,PIT,WR,6,72,40,55.6,478,6,...,6.6,12.0,0,0,0.0,0,0,0,14.0,83.80

In [15]:
stats18.drop(['Rank', 'Played', 'ReceivingTargets', 'ReceptionPercentage', 'ReceivingLong',
                   'ReceivingYardsPerTarget', 'ReceivingYardsPerReception', 'RushingAttempts',
                   'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles',
                   'FumblesLost', 'FantasyPointsPerGame', 'FantasyPoints'], axis=1, inplace=True)
stats18.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Tyreek Hill,KC,WR,34,567,6
1,Adam Thielen,MIN,WR,58,712,4
2,Emmanuel Sanders,DEN,WR,46,603,3
3,Davante Adams,GB,WR,47,557,6
4,Antonio Brown,PIT,WR,40,478,6

In [16]:
# Combine the Data Frames for WRâ€™s

wr_frames = [stats12, stats13, stats14, stats15, stats16, stats17, stats18]
wr_result = pd.concat(wr_frames)

In [19]:
wr_result.head()

,Name,Team,Position,Receptions,ReceivingYards,ReceivingTouchdowns
0,Calvin Johnson,DET,WR,122,1964,5
1,Brandon Marshall,CHI,WR,118,1508,11
2,Dez Bryant,DAL,WR,92,1382,12
3,AJ Green,CIN,WR,97,1350,11
4,Demaryius Thomas,DEN,WR,94,1434,10